---
title: "Cluster1_analysis_visualisation"
author: "Michael Monsonego"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: 
    fig_crop: no
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.width=17) 
knitr::opts_chunk$set(cache = TRUE) 
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```
tSNE plot
=====
```{r message=FALSE, warning=FALSE, fig.height= 5, fig.width=7}

library(dplyr)
library(Seurat)
library(patchwork)
library(tidyverse)
library(sleepwalk)
library(gridExtra)
library(future)
library(reshape2)
library(reticulate)
library(ggplot2)
library(plyr)
library(stringr)
library(RColorBrewer)
library(grid)
library(cowplot)
library(ggsignif)
library(DT)
library(Cairo)
library(snakecase)
library(glue)
library(ggrepel)


setwd("D:/Michael/git_check/tils")
# setwd("C:/Users/michael monsonego/Documents/tils") #M# update between computers(git)

x1=4.6
clus1 = readRDS("objects/clus1_no_cd4_second_sub_14_0.5.rds")

DimPlot(clus1 , reduction = "tsne", label= TRUE, pt.size=0.5, label.size = 6)
ggsave(file = "figures/clus1/tsne.png", dpi=300, width=8, height=6)
TSNEPlot(clus1, group.by ="Treatment", cols= c("#ff7f0e", "#1f77b4"), pt.size=0.5)+
  theme(legend.text=element_text(size=20))
ggsave(file = "figures/clus1/tsne_by_treatment.png", dpi=300, width=8, height=6)

```
### checking 
```{r cache=T, fig.height=x1*2, warning=FALSE}
DefaultAssay(clus1) <- "RNA"
FeaturePlot(clus1, features = c("ZNF831", "HIVEP1"), order=TRUE,pt.size=1, reduction="tsne", ncol=3)
ggsave(file = "figures/clus1/checking.png", dpi=300, width=15, height=6)
```

```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height=16}
VlnPlot(clus1, features = c("ZNF831", "HIVEP1"), 
  assay = "RNA", 
  stack = TRUE, 
  flip = TRUE, 
  split.by = "Treatment"
) + 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
    ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/checking1.png", dpi=300, width=15, height=x1*2)

VlnPlot(clus1, features = c("ZNF831", "HIVEP1"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  group.by = "Treatment",
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/checking2.png", dpi=300, width=4, height=x1)
```

Top DE genes
--------------
```{r echo=FALSE, cashe = TRUE}
Top50Markers <- read.delim("excels/cluster_1_DE_genes_19_8_24.csv", sep = ",", header = T, quote="\"", check.names=FALSE)
Top50Markers$avg_log2FC <- Top50Markers$avg_log2FC %>% round(2)
Top50Markers <- Top50Markers[,c("cluster","gene", "avg_log2FC", "p_val")] 
datatable(Top50Markers, rownames = FALSE, filter = 'top', colnames = c('Cluster #', 'Gene Name', "log2(FC)", 'P.value'))
```

```{r eval=FALSE, fig.height=8, message=FALSE, warning=FALSE, include=FALSE}
## Contribution of each group 
#M# unnormalized counts per cluster per treatment.
ggplot(clus1@meta.data, aes(x=clus1@active.ident, fill=Treatment)) + geom_bar(stat="count",position=position_dodge())+
    scale_fill_manual(values= c("#CFBAE1", "#5C7D9D"))+
    theme_classic()+
    labs(x="")+
    theme(legend.title=element_text(size=18),legend.text= element_text(size=14), 
          axis.text.x=element_text(size=12,angle=45, hjust=1))+labs(title = "unnormalized counts per cluster per treatment")

ggsave(file = "figures/clus1/unnormalized_counts_per_cluster_per_treatment.png", dpi=300, width=15, height=10)
```

```{r eval=FALSE, fig.height=8, message=FALSE, warning=FALSE, include=FALSE}
#M# percentage of contribution to each cluster per treatment
ggplot(clus1@meta.data, aes(x=clus1@active.ident, fill=Treatment)) + geom_bar(position="fill")+
    scale_fill_manual(values= c("#CFBAE1", "#5C7D9D"))+
    theme_classic()+
    labs(x="")+
    theme(legend.title=element_text(size=18),legend.text= element_text(size=14), 
          axis.text.x=element_text(size=12,angle=45, hjust=1))+labs(title = "percentage of contribution to each cluster per treatment")
ggsave(file = "figures/clus1/percentage_of_contribution_stacked_bar_plot.png", dpi=300, width=10, height=10)
```

```{r eval=FALSE, fig.height=8, message=FALSE, warning=FALSE, include=FALSE}
## unnormalized contribution per patient 

Sample_Names_vec <- c("N1","N2","N3","N4")
for (sample in Sample_Names_vec) {
  Tsub = clus1@meta.data[clus1@meta.data$orig.ident == sample, ]
 ggplot(Tsub, aes(x=Tsub$seurat_clusters, fill=Treatment)) + geom_bar(stat="count",position=position_dodge())+
    scale_fill_manual(values= c("#CFBAE1"))+
    theme_classic()+
    labs(x="")+
    theme(legend.title=element_text(size=18),legend.text= element_text(size=14), 
          axis.text.x=element_text(size=12,angle=45, hjust=1))+labs(title = glue({sample}, " : unnormalized counts per cluster per treatment"))
  ggsave(filename = glue({sample}, "_unnormalized_counts_per_cluster_per_treatment.png"), path = "figures/clus1/", dpi=300, width=10, height=10)
}

Sample_Names_vec <- c("R1","R2","R3","R4")
for (sample in Sample_Names_vec) {
  Tsub = clus1@meta.data[clus1@meta.data$orig.ident == sample, ]
 ggplot(Tsub, aes(x=Tsub$seurat_clusters, fill=Treatment)) + geom_bar(stat="count",position=position_dodge())+
    scale_fill_manual(values= c("#5C7D9D"))+
    theme_classic()+
    labs(x="")+
    theme(legend.title=element_text(size=18),legend.text= element_text(size=14), 
          axis.text.x=element_text(size=12,angle=45, hjust=1))+labs(title = glue({sample}, " : unnormalized counts per cluster per treatment"))
  ggsave(filename = glue({sample}, "_unnormalized_counts_per_cluster_per_treatment.png"), path = "figures/clus1/", dpi=300, width=10, height=10)
}
```

bar plots
=====
## normalized contribution per patient 
```{r echo=FALSE, fig.height=6, fig.width=10}
frque <- table(Idents(clus1), clus1$Treatment)
frque <- as.data.frame(frque)
frque <- frque %>% dplyr::rename(Cluster = Var1, Treatment = Var2)
frque$Treatment <- factor(frque$Treatment)

frque <- ddply(frque, .(Treatment),  transform, percentperstatus   = Freq/sum(Freq))
frque <- ddply(frque, .(Cluster), transform, percentpercluster  = Freq/sum(Freq))
frque <- ddply(frque, .(Cluster), transform, normalizedppstatus = percentperstatus/sum(percentperstatus)*100)
frque <- ddply(frque, .(Treatment),  transform, normalizedpcluster = percentpercluster/sum(percentpercluster))

mfrque <- table(Idents(clus1), clus1$orig.ident)
mfrque <- as.data.frame(mfrque)
mfrque <- mfrque %>% dplyr::rename(Cluster = Var1, patient = Var2)

mfrque <- ddply(mfrque, .(patient),  transform, percentperstatus   = Freq/sum(Freq))
mfrque <- ddply(mfrque, .(Cluster), transform, percentpercluster  = Freq/sum(Freq))
mfrque <- ddply(mfrque, .(Cluster), transform, normalizedppstatus = percentperstatus/sum(percentperstatus)*100)
mfrque <- ddply(mfrque, .(patient),  transform, normalizedpcluster = percentpercluster/sum(percentpercluster))


p3 <- ggplot(mfrque, aes(x = Cluster, y = normalizedppstatus, fill = patient)) +
 theme_minimal() +
 geom_bar(stat = "identity", width = 0.7,position="dodge") +
   scale_fill_manual(values= c("#CFBAE1", "#A8A5CA", "#8291B3", "#5C7D9D", "#FF6F61", "#D78459", "#AF9A52", "#88B04B"))+
 ggtitle("Normalized Cluster Counts") +
 ylab("Normalized Proportions in %") +
 theme(
   axis.text.x  = element_text(angle = 67, hjust = 1, size = 11, color = "black"),
   axis.text.y  = element_text(size = 11, color = "black"),
   axis.title.x = element_text(size = 13, color = "black"),
   axis.title.y = element_text(size = 13, color = "black"),
   title = element_text(size = 13),
   legend.justification = "top",
   panel.border = element_blank()) +
 geom_hline(yintercept = 20, linetype='dotted')
  
  
p1 <- ggplot(frque, aes(x = Cluster, y = normalizedppstatus, fill = Treatment)) +
 theme_minimal() +
 geom_bar(stat = "identity", width = 0.7,position="dodge") +
 scale_fill_manual(values= c("#ff7f0e", "#1f77b4"))+
 ggtitle("Normalized Cluster Counts") +
 ylab("Normalized Proportions in %") +
 theme(
   axis.text.x  = element_text(angle = 67, hjust = 1, size = 11, color = "black"),
   axis.text.y  = element_text(size = 11, color = "black"),
   axis.title.x = element_text(size = 13, color = "black"),
   axis.title.y = element_text(size = 13, color = "black"),
   title = element_text(size = 13),
   legend.justification = "top",
   panel.border = element_blank()) +
 geom_hline(yintercept = 33.3, linetype='dotted') 

p2<-ggplot(frque, aes(x= Cluster, y= Freq, fill = Treatment)) +
 theme_minimal() +
 geom_bar(stat = "identity", width = 0.7) +
 scale_fill_manual(values= c("#ff7f0e", "#1f77b4"))+
 ggtitle("Cluster Counts") + ylab("Cell counts\n") +
 theme(
   axis.text.x  = element_text(angle = 67, hjust = 1, size = 11, color = "black"),
   axis.text.y  = element_text(size = 11, color = "black"),
   axis.title.x = element_text(size = 13, color = "black"),
   axis.title.y = element_text(size = 13, color = "black"),
   title = element_text(size = 13),
   legend.justification = "top",
   panel.border = element_blank())

p2+p1+plot_layout(guides = "collect")+plot_annotation(tag_levels = 'A') 
ggsave(file = "figures/clus1/unnormalized_and_normalized_contribution_per_patient.png", dpi=300, width=14, height=10)

p3
ggsave(file = "figures/clus1/normalized_cluster_counts.png", dpi=300, width=14, height=10)
```

volcano plot
=====
```{r fig.height=10}
DE_genes <- read.csv("excels/DE_genes_res_nonRes_clus1_no_5.csv")

DE_genes$Significance <- "Not Significant"
DE_genes$Significance[DE_genes$p_val_adj < 0.05 & DE_genes$avg_log2FC > 0] <- "Upregulated"
DE_genes$Significance[DE_genes$p_val_adj < 0.05 & DE_genes$avg_log2FC < 0] <- "Downregulated"

genes_of_interest <- c("ILR7", "GNZMB")  # replace with gene names of interest to see on volcano plot

top_1000_genes <- DE_genes %>%
  arrange(p_val_adj) %>%
  head(1000) %>%
  pull(gene) 

label_genes <- union(genes_of_interest, top_1000_genes)
DE_genes$Label <- ifelse(DE_genes$gene %in% label_genes, DE_genes$gene, NA)

ggplot(DE_genes, aes(x = avg_log2FC, y = -log10(p_val_adj))) +
  geom_point(aes(color = Significance)) +
  scale_color_manual(values = c("Not Significant" = "grey", "Upregulated" = "blue", "Downregulated" = "red")) +
  theme_minimal() +
  labs(title = "Volcano Plot", x = "Log2 Fold Change", y = "-Log10 Adjusted P-value") +
  theme(legend.title = element_blank()) +
  geom_text_repel(aes(label = Label), 
                  box.padding = 0.35, 
                  point.padding = 0.3, 
                  max.overlaps = 10, 
                  segment.color = 'grey50')+
  ylim(0, 300)
ggsave(file = "figures/clus1/volcano.png", dpi=300, width=15, height=10)

```
Top DE genes between responders and non-responders
--------------
```{r}
Top100Markers <- read.delim("excels/Top100Markers_per_treatment_tils_1_.5_no_5.csv", sep = ",", header = T, quote="\"", check.names=FALSE)
Top100Markers$avg_log2FC <- Top100Markers$avg_log2FC %>% round(2)
Top100Markers <- Top100Markers[,c("gene", "avg_log2FC", "p_val")] 
datatable(Top100Markers, rownames = FALSE, filter = 'top', colnames = c('Gene Name', "log2(FC)", 'P.value'))
```

Markers
=====

### Proliferation Markers

```{r fig.height=x1*1, cache=TRUE}
Prolif <- c("TOP2A","MKI67")
FeaturePlot(clus1, features = Prolif, label.size = 8, pt.size = 1, label=T, ncol = 2, order = T,reduction = "tsne")
ggsave(file = "figures/clus1/Proliferation_Markers.png", dpi=300, width=20, height=x1*2)
```

### T Cells Markers
```{r cache=T, fig.height=x1*2,warning=FALSE}
DefaultAssay(clus1) <- "RNA"
Ts <- c('Cd4', 'Cd8a', 'Cd3d','Cd3e','Cd3g',"PTPRC")
Ts <- toupper(Ts)
FeaturePlot(clus1, features = Ts, label.size = 8, pt.size = 1, label=T, ncol = 3, order = T,reduction = "tsne")
ggsave(file = "figures/clus1/T_Cells_Markers.png", dpi=300, width=15, height=x1*2)
```
### checking 
```{r cache=T, fig.height=x1*2, warning=FALSE}
FeaturePlot(clus1, features = c("ENTPD1", "GZMB", "PRF1", "CD40LG","CD8A","CD8B"), order=TRUE,pt.size=1, reduction="tsne", ncol=3)
ggsave(file = "figures/clus1/checking.png", dpi=300, width=15, height=x1*2)
```

```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height=16}
VlnPlot(clus1, features = c("ENTPD1", "GZMB", "PRF1", "CD40LG","CD8A","CD8B"), 
  assay = "RNA", 
  stack = TRUE, 
  flip = TRUE, 
  split.by = "Treatment"
) + 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
    ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/checking1.png", dpi=300, width=15, height=x1*2)

VlnPlot(clus1, features = c("ENTPD1", "GZMB", "PRF1", "CD40LG","CD8A","CD8B"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  group.by = "Treatment",
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/checking2.png", dpi=300, width=4, height=x1*2)

VlnPlot(clus1, features = c("ENTPD1", "GZMB", "PRF1", "CD40LG","CD8A","CD8B"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/checking3.png", dpi=300, width=15, height=x1*2)
```

### NKT markers
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.width=10, fig.height= 10}
Ts <- c("Klrb1", "Itga2", "Cxcr3", "Trdc", "Gzma", "Itgam",  "Gzmb", "Ncr1", "Gzmk")
Ts <- toupper(Ts)
FeaturePlot(clus1, features = Ts, order=TRUE,pt.size=0.5, reduction="tsne", ncol=3)
ggsave(file = "figures/clus1/features_NKT.png", dpi=300, width=10, height=10)
```
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height=20}
VlnPlot(clus1, features = Ts, 
  assay = "RNA", 
  stack = TRUE, 
  flip = TRUE, 
  split.by = "Treatment"
) + 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
    ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/checking1.png", dpi=300, width=15, height=x1*2)
```
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height=40}

VlnPlot(clus1, features = Ts,
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  group.by = "Treatment",
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/checking2.png", dpi=300, width=4, height=x1*2)
```
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height=20}
VlnPlot(clus1, features = Ts,
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/checking3.png", dpi=300, width=15, height=x1*2)
```





### a. activation/exhaustion markers
```{r message=FALSE, warning=FALSE, fig.height= 16}
# activation / exhaustion markers
FeaturePlot(clus1, features = c("PDCD1","HAVCR2","LAG3","TIGIT","TNFRSF4","TNFRSF9","ICOS","CTLA4","KLRD1","IRF8","KLRC1","TOX"), order=TRUE,pt.size=1, reduction="tsne", ncol=3)
ggsave(file = "figures/clus1/features_T_activation.png", dpi=300, width=10, height=10)
```

```{r message=FALSE, warning=FALSE, fig.height=20}
VlnPlot(clus1, features = c("PDCD1","HAVCR2","LAG3","TIGIT","TNFRSF4","TNFRSF9"), 
  assay = "RNA", 
  stack = TRUE, 
  flip = TRUE, 
  split.by = "Treatment"
) + 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
    ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
 ggsave(filename = "vln_activation_exhastion_cluster_by_treatment_1.png" , path = "figures/clus1/", dpi=300, width=12, height=10)

VlnPlot(clus1, features = c("PDCD1","HAVCR2","LAG3","TIGIT","TNFRSF4","TNFRSF9"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  group.by = "Treatment",
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/vln_activation_exhastion_by_treatment_1.png", dpi=300, width=4, height=10)

VlnPlot(clus1, features = c("PDCD1","HAVCR2","LAG3","TIGIT","TNFRSF4","TNFRSF9"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/vln_activation_exhastion_by_cluster_1.png", dpi=300, width=6, height=10)

##

VlnPlot(clus1, features = c("ICOS","CTLA4","KLRD1","IRF8","KLRC1","TOX"),  
  assay = "RNA", 
  stack = TRUE, 
  flip = TRUE, 
  split.by = "Treatment"
) + 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
    ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/Vln_T_activation_exhaustion_cluster_by_treatment_2.png", dpi=300, width=8, height=10, limitsize=FALSE)

VlnPlot(clus1, features = c("ICOS","CTLA4","KLRD1","IRF8","KLRC1","TOX"), 
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  group.by = "Treatment",
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/Vln_T_activation_exhaustion_by_treatment_2.png", dpi=300, width=4, height=10, limitsize=FALSE)

VlnPlot(clus1, features = c("ICOS","CTLA4","KLRD1","IRF8","KLRC1","TOX"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/Vln_T_activation_exhaustion_by_cluster_2.png", dpi=300, width=6, height=10, limitsize=FALSE)

```

### b. effector markers 
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height=16}
FeaturePlot(clus1, features = c("GZMB","PRF1","IFNG","MKI67","GZMC","GZMA","KLRG1","IL7R","CD52"),order=TRUE,pt.size=1, reduction="tsne", ncol=3)
ggsave(file = "figures/clus1/features_T_effector.png", dpi=300, width=8, height=10)
```
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height=10}
VlnPlot(clus1, features = c("GZMB","PRF1","IFNG","TNF"), 
  assay = "RNA", 
  stack = TRUE, 
  flip = TRUE, 
  split.by = "Treatment"
) + 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
    ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/Vln_T_effector_cluster_by_treatment_1.png", dpi=300, width=8, height=10, limitsize=FALSE)

VlnPlot(clus1, features = c("GZMB","PRF1","IFNG","TNF"), 
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  group.by = "Treatment",
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/Vln_T_effector_by_treatment_1.png", dpi=300, width=4, height=10, limitsize=FALSE)

VlnPlot(clus1, features = c("GZMB","PRF1","IFNG","TNF"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/Vln_T_effector_by_cluster_1.png", dpi=300, width=6, height=10, limitsize=FALSE)

##

VlnPlot(clus1, features = c("GZMC","GZMA","KLRG1","CD52"), 
  assay = "RNA", 
  stack = TRUE, 
  flip = TRUE, 
  split.by = "Treatment"
) + 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
    ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/Vln_T_effector_cluster_by_treatment_2.png", dpi=300, width=8, height=10, limitsize=FALSE)

VlnPlot(clus1, features = c("GZMC","GZMA","KLRG1","CD52"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  group.by = "Treatment",
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/Vln_T_effector_by_treatment_2.png", dpi=300, width=4, height=10, limitsize=FALSE)

VlnPlot(clus1, features = c("GZMC","GZMA","KLRG1","CD52", fill.by = "ident"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/Vln_T_effector_by_cluster_2.png", dpi=300, width=6, height=10, limitsize=FALSE)

```

### CD69 + CD39
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height= x1, fig.width=8}
# naive
FeaturePlot(clus1, features = c("CD69","ENTPD1"),order=TRUE,pt.size=1, reduction="tsne", ncol=2)
ggsave(file = "figures/clus1/CD69.png", dpi=300, width=8, height=10)
```
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height= x1}
VlnPlot(clus1, features = c("CD69","ENTPD1"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/Vln_CD69.png", dpi=300, width=6, height=10, limitsize=FALSE)

VlnPlot(clus1, features = c("CD69"), 
  assay = "RNA", 
  flip = TRUE, 
  split.by = "Treatment"
) + 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
    ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)

VlnPlot(clus1, features = c("ENTPD1"), 
  assay = "RNA", 
  flip = TRUE, 
  split.by = "Treatment"
) + 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
    ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
```


### c. naive/stem-like (naive or memory cells)
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height=x1*2}
# memory 
FeaturePlot(clus1, features = c("SELL","CD44","IL7R","CCR7","TCF7","CXCR6"),order=TRUE,pt.size=1, reduction="tsne", ncol=3)
ggsave(file = "figures/clus1/features_T_memory.png", dpi=300, width=10, height=8)
```
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height=20}
VlnPlot(clus1, features = c("SELL","CD44","IL7R","CCR7","TCF7","CXCR6"), 
  assay = "RNA", 
  stack = TRUE, 
  flip = TRUE, 
  split.by = "Treatment"
) + 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
    ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/naive_response_cluster.png", dpi=300, width=30, height=40)

VlnPlot(clus1, features = c("SELL","CD44","IL7R","CCR7","TCF7","CXCR6"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  group.by = "Treatment",
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/naive_response.png", dpi=300, width=30, height=40)

VlnPlot(clus1, features = c("SELL","CD44","IL7R","CCR7","TCF7","CXCR6"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
ggsave(file = "figures/clus1/naive_cluster.png", dpi=300, width=30, height=40)
```


### d. effector memory markers
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height= x1*4}
FeaturePlot(clus1, features = c("BACH2","PRDM1","IL7R","CD44","CX3CR1","ID2","KLF2","KLRG1","LEF1","STAT4","TBX21","ZEB2"),order=TRUE,pt.size=1, reduction="tsne", ncol=3)
ggsave(file = "figures/clus1/features_T_effector memory.png", dpi=300, width=30, height=40)
```
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height=x1*12}
VlnPlot(clus1, features = c("BACH2","PRDM1","IL7R","CD44","CX3CR1","ID2","KLF2","KLRG1","LEF1","STAT4","TBX21","ZEB2"), 
  assay = "RNA", 
  stack = TRUE, 
  flip = TRUE, 
  split.by = "Treatment"
) + 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
    ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)

VlnPlot(clus1, features = c("BACH2","PRDM1","IL7R","CD44","CX3CR1","ID2","KLF2","KLRG1","LEF1","STAT4","TBX21","ZEB2"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  group.by = "Treatment",
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)

VlnPlot(clus1, features = c("BACH2","PRDM1","IL7R","CD44","CX3CR1","ID2","KLF2","KLRG1","LEF1","STAT4","TBX21","ZEB2"), 
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
```

### e. central memory markers
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height= x1*5}
FeaturePlot(clus1, features = c("TCF7","BACH2","BCL16","CCR7","IL7R","CD27","CD44","SELL","ID3","KLF2","LCR7","LEF1","SLAMF6","STAT3","TFAP4"),order=TRUE,pt.size=1, reduction="tsne", ncol=3)
ggsave(file = "figures/clus1/features_T_central memory.png", dpi=300, width=30, height=50, limitsize=FALSE)
```
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height=x1*12}
VlnPlot(clus1, features = c("TCF7","BACH2","BCL16","CCR7","IL7R","CD27","CD44","SELL","ID3","KLF2","LCR7","LEF1","SLAMF6","STAT3","TFAP4"), 
  assay = "RNA", 
  stack = TRUE, 
  flip = TRUE, 
  split.by = "Treatment"
) + 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
    ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)

VlnPlot(clus1, features = c("TCF7","BACH2","BCL16","CCR7","IL7R","CD27","CD44","SELL","ID3","KLF2","LCR7","LEF1","SLAMF6","STAT3","TFAP4"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  group.by = "Treatment",
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)

VlnPlot(clus1, features = c("TCF7","BACH2","BCL16","CCR7","IL7R","CD27","CD44","SELL","ID3","KLF2","LCR7","LEF1","SLAMF6","STAT3","TFAP4"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
```



### f. resident memory markers
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height= x1*8}
FeaturePlot(clus1, features = c("PRDM1","ITGAE","IL7R","CD44","ITGA1","CD69","CRTAM","DUSP6","EGR2","FOSB","FOXO3","GZMA","GZMB","ZNF683","ID3","IL2RA","IRF4","JUN","JUNB","MYC","NR4A1","RGS1"), order=TRUE, pt.size=1, reduction="tsne", ncol=3)
ggsave(file = "figures/clus1/features_T_resident memory.png", dpi=300, width=30, height=80, limitsize=FALSE)
```
```{r message=FALSE, warning=FALSE, cache= TRUE, fig.height=x1*12}
VlnPlot(clus1, features = c("PRDM1","ITGAE","IL7R","CD44","ITGA1","CD69","CRTAM","DUSP6","EGR2","FOSB","FOXO3","GZMA","GZMB","ZNF683","ID3","IL2RA","IRF4","JUN","JUNB","MYC","NR4A1","RGS1"), 
  assay = "RNA", 
  stack = TRUE, 
  flip = TRUE, 
  split.by = "Treatment"
) + 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
    ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)

VlnPlot(clus1, features = c("PRDM1","ITGAE","IL7R","CD44","ITGA1","CD69","CRTAM","DUSP6","EGR2","FOSB","FOXO3","GZMA","GZMB","ZNF683","ID3","IL2RA","IRF4","JUN","JUNB","MYC","NR4A1","RGS1"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  group.by = "Treatment",
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)

VlnPlot(clus1, features = c("PRDM1","ITGAE","IL7R","CD44","ITGA1","CD69","CRTAM","DUSP6","EGR2","FOSB","FOXO3","GZMA","GZMB","ZNF683","ID3","IL2RA","IRF4","JUN","JUNB","MYC","NR4A1","RGS1"),
  assay = "RNA",
  stack=TRUE,
  flip= TRUE,
  fill.by ="ident"
  )+ 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 70, hjust = 1, size = 16, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 24, face = "italic"),
    axis.title.y = element_text(size = 20, face = "bold"),
    axis.ticks.y = element_line(size = 0.5),
    strip.text.y = element_text(angle = 0, size = 16, face = "bold")
  ) +
  geom_boxplot(alpha = 0.3, show.legend = FALSE)
```

### h. T cells features signatures 
```{r fig.height=3, fig.width=3, message=FALSE, warning=FALSE}

il2 <- list(c("Shc1","Stat5b","Lck","Stat5a","Jak3","Syk","Csnk2a1","Elk1","Grb2","Hras","Il2","Il2ra","Il2rb","Map2k1","Sos1","Csnk2a2","Fos","Jun","Mapk3","Il2rg","Mapk8","Raf1","Jak1"))
clus1 = AddModuleScore(object = clus1, features = il2, name = "il2", assay = "RNA")
a <- FeaturePlot(object = clus1, features = "il21", reduction = "tsne", cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "il2", subtitle = "Il2,Il2ra,Il2rb..")+ theme(plot.subtitle = element_text(hjust = 0.5))
a
ggsave(file = "figures/clus1/il2.png", dpi=300, width=5, height=5)


il2_r <- list(c("Bad", "Bcl2", "Cbl", "Cflar", "Crkl", "E2f1", "Fas", "Fasl",	"Fos", "Grb2", "Hras", "Ikzf3", "Il2ra", "Il2rb", "Il2rg", "Irs1", "Jak1", "Jak3", "Mapk1", "Mapk3", "Myc", "Nmi", "Pik3ca", "Pik3cg", "Pik3r1", "Ptpn6", "Raf1", "Rps6kb1", "Shc1", "Socs1", "Socs3", "Sos1", "Stat5a", "Stat5b", "Syk"))
clus1 = AddModuleScore(object = clus1, features = il2_r, name = "il2_r", assay = "RNA")
a <- FeaturePlot(object = clus1, features = "il2_r1", reduction = "tsne", cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "il2_R", subtitle = "Il2ra, Il2rb, Il2rg...")+ theme(plot.subtitle = element_text(hjust = 0.5))
a
ggsave(file = "figures/clus1/il2_R_.png", dpi=300, width=5, height=5)



persistance_up <- list(c('KLRB1','ZNF683','ITGB1','IL7R','LIME1', "S1PR1", "TIMP1", "TBXAS1", "KLF2", "LTB", "UBXN11", "CD40LG", "VCL", "RASA3", "SCML4", "MYC", "P2RY8"))
clus1 = AddModuleScore(object = clus1, features = persistance_up, name = "persistance_up", assay = "RNA")
a <- FeaturePlot(object = clus1, features = "persistance_up1", reduction = "tsne", cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "persistance_up", subtitle = "KLRB1, ZNF683, ITGB1..")+ theme(plot.subtitle = element_text(hjust = 0.5))
a
ggsave(file = "figures/clus1/persistance_up.png", dpi=300, width=5, height=5)



CD8_memory_list = list(c("IL7R","CD44","CXCR6"))
clus1 = AddModuleScore(object = clus1, features = CD8_memory_list, name = "CD8_memory", assay = "RNA")
a <- FeaturePlot(object = clus1, features = "CD8_memory1", reduction = "tsne", cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "CD8+ memory", subtitle = "(IL7R,CD44,CXCR6)")+ theme(plot.subtitle = element_text(hjust = 0.5))
a
ggsave(file = "figures/clus1/CD8_memory_Cxcl10.png", dpi=300, width=5, height=5)

activated_list = list(c("PDCD1","KLRD1","GZMA"))
clus1 = AddModuleScore(object = clus1, features = activated_list, name = "activated", assay = "RNA")
b <- FeaturePlot(object = clus1, features = "activated1", reduction = "tsne", cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "activated_CD8+activated", subtitle = "(PDCD1,KLRD1,GZMA)")+ theme(plot.subtitle = element_text(hjust =0.5))
b
ggsave(file = "figures/clus1/activated.png", dpi=300, width=5, height=5)

effector_memory_list = list(c("ID2","STAT3","GZMB","PRF1","IL7R"))
clus1 = AddModuleScore(object = clus1, features = effector_memory_list, name = "effector_memory", assay = "RNA")
c <- FeaturePlot(object = clus1, features = "effector_memory1", reduction = "tsne", cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "CD8+ effector memory", subtitle = "(ID2,STAT3,GZMB,PRF1,IL7R)")+ theme(plot.subtitle = element_text(hjust =0.5))
c
ggsave(file = "figures/clus1/effector_memory_Tregs.png", dpi=300, width=5, height=5)

cytotoxic_list = list(c("GZMB","GZMC","GRZMF"))
clus1 = AddModuleScore(object = clus1, features = cytotoxic_list, name = "cytotoxic", assay = "RNA")
d <- FeaturePlot(object = clus1, features = "cytotoxic1", reduction = "tsne", cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "CD8+ cytotoxic", subtitle = "(GZMB,GZMC,GRZMF)")+ theme(plot.subtitle = element_text(hjust =0.5))
d
ggsave(file = "figures/clus1/cytotoxic_Tregs.png", dpi=300, width=5, height=5)


CD8_naive_memory_list = list(c("CD8A","CD4","SELL","CCR7","TCF7","LEF1","CD8","ITGAE","CXCR3","GZMA","SELL","CCR7"))
clus1 = AddModuleScore(object = clus1, features = CD8_naive_memory_list, name = "CD8_naive_memory", assay = "RNA")
e <- FeaturePlot(object = clus1, features = "CD8_naive_memory1", reduction = "tsne", cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "CD8+ naive/memory", subtitle = "(CD8A,CD4,SELL,CCR7,TCF7,LEF1,CD8,ITGAE,CXCR3,GZMA,SELL,CCR7)")+ theme(plot.subtitle = element_text(hjust =0.5))
e
ggsave(file = "figures/clus1/CD8_naive_memory_Tregs.png", dpi=300, width=5, height=5)


CD4_CD8_naive_memory_list = list(c("CD8A","CD4","SELL","CCR7","TCF7","LEF1"))
clus1 = AddModuleScore(object = clus1, features = CD4_CD8_naive_memory_list, name = "CD4_CD8_naive_memory", assay = "RNA")
f <- FeaturePlot(object = clus1, features = "CD4_CD8_naive_memory1", reduction = "tsne", cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "CD4+ CD8+ naive/memory", subtitle = "(CD8A,CD4,SELL,CCR7,TCF7,LEF1)")+ theme(plot.subtitle = element_text(hjust =0.5))
f
ggsave(file = "figures/clus1/CD4_CD8_naive_memory_CD4_CD8_naive_memory.png", dpi=300, width=5, height=5)

proliferating_list = list(c("CD8","MKI67"))
clus1 = AddModuleScore(object = clus1, features = proliferating_list, name = "proliferating", assay = "RNA")
g <- FeaturePlot(object = clus1, features = "proliferating1", reduction = "tsne", cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "CD8+ proliferating", subtitle = "(Cd8, Mki67)")+ theme(plot.subtitle = element_text(hjust =0.5))
g
ggsave(file = "figures/clus1/proliferating_CD8+proliferating.png", dpi=300, width=5, height=5)

Tregs_list = list(c("CD4","FOXP3","IL2RA","ICOS","TNFRSF4"))
clus1 = AddModuleScore(object = clus1, features = Tregs_list, name = "Tregs", assay = "RNA")
h <- FeaturePlot(object = clus1, features = "Tregs1", reduction = "tsne", cols=c("grey","grey","#e46467", "#b33336", "#A73033"))+labs(title = "Tregs", subtitle = "(Cd4, Foxp3,Il2ra, Icos, Tnfrsf4)")+ theme(plot.subtitle = element_text(hjust =0.5))
h
ggsave(file = "figures/clus1/Tregs_Tregs.png", dpi=300, width=5, height=5)



#M# saveRDS(clus1, file = "objects/clus1_with_sigs.rds")


```

```{r eval=FALSE, fig.height=4, fig.width=7, cache=FALSE, include=FALSE}
## Annotation

Idents(clus1) <- 'seurat_clusters'
clus1 <- RenameIdents(clus1, "0" = "0_stem like/memory",
                                 "1" = "1_exhausted",
                                 "2" = "2_Teff",
                                 "3" = "3_proliferation",
                                 "4" = "4_progenitors_exhausted")
                        
p <- DimPlot(clus1, reduction = "tsne", label = F, label.size = 3.5)
LabelClusters(p, id = "ident",  fontface = "bold",position = "median")
#M# saveRDS(clus1, file = "objects/clus1_no_cd4_second_sub_14_0.5.rds")
```


&nbsp;
<hr />
<p style="text-align: center;">Work by Michael Monsonego</a></p>
<p style="text-align: center;"> <a href="https://www.asafmadilab.com/">Madi Lab</a></p>
&nbsp;




















